# Example: https://docs.blender.org/manual/en/latest/advanced/extensions/getting_started.html#manifest
schema_version = "1.0.0"
id = "pie"
version = "1.0.0"
name = "MyPie"
tagline = "My personal pie menu"
maintainer = "tfAnimator <ani@tfanim.com>"
type = "add-on"
website = "https://tfanim.com"
tags = ["User Interface"]
blender_version_min = "5.2.0"
#blender_version_max = "4.5.0"
license = [ "SPDX:GPL-3.0-or-later" ]
